apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub 
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:3.0.1-aluminum
        ports:
          - containerPort: 4444 
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  ports:
  - port: 4444 
    targetPort: 4444 
    name: port0
  selector:
    app: selenium-hub
  type: NodePort
  sessionAffinity: None
